# Generated by Django 4.2.7 on 2026-03-07 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reservation_number",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("voyageur", models.IntegerField()),
                (
                    "amadeus_offer_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amadeus_pnr", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "amadeus_booking_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "last_confirmed_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("price_confirmed_at", models.DateTimeField(null=True)),
                (
                    "confirmed_offer_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PRICE", "En attente de confirmation prix"),
                            ("PRICE_CONFIRMED", "Prix confirmé"),
                            ("BOOKING_PENDING", "Réservation en cours"),
                            ("CONFIRMED", "Confirmée"),
                            ("CANCELLED", "Annulée"),
                            ("EXPIRED", "Expirée"),
                            ("FAILED", "Échouée"),
                        ],
                        default="PENDING_PRICE",
                        max_length=20,
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("ALLER_SIMPLE", "Aller simple"),
                            ("ALLER_RETOUR", "Aller-retour"),
                            ("MULTI_DESTINATION", "Multi-destination"),
                        ],
                        max_length=20,
                    ),
                ),
                ("search_params", models.JSONField(default=dict)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="DZD", max_length=3)),
                ("expiry_date", models.DateTimeField(blank=True, null=True)),
                ("confirmation_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reservation_number"],
                        name="reservation_reserva_3144d8_idx",
                    ),
                    models.Index(
                        fields=["amadeus_pnr"], name="reservation_amadeus_ac8f37_idx"
                    ),
                    models.Index(
                        fields=["voyageur", "-created_at"],
                        name="reservation_voyageu_36bd9f_idx",
                    ),
                    models.Index(
                        fields=["status"], name="reservation_status_f1a03a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offered_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "confirmed_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(max_length=3)),
                ("amadeus_offer_id", models.CharField(max_length=100)),
                ("offer_data", models.JSONField(default=dict)),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_confirmations",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="DZD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("COMPLETED", "Complété"),
                            ("FAILED", "Échoué"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CARD", "Carte bancaire"),
                            ("PAYPAL", "PayPal"),
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("CASH", "Espèces"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reservation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PassengerReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passenger", models.IntegerField()),
                ("check_in_status", models.BooleanField(default=False)),
                ("seat_number", models.CharField(blank=True, max_length=10, null=True)),
                ("baggage_quantity", models.PositiveSmallIntegerField(default=0)),
                ("price_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amadeus_traveler_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passenger_reservations",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "unique_together": {("reservation", "passenger")},
            },
        ),
        migrations.CreateModel(
            name="FlightSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("segment_number", models.PositiveSmallIntegerField()),
                ("origin", models.CharField(max_length=3)),
                ("destination", models.CharField(max_length=3)),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("flight_data", models.JSONField(default=dict)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per_passenger_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flight_segments",
                        to="reservations.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["segment_number"],
                "unique_together": {("reservation", "segment_number")},
            },
        ),
    ]
