# Generated by Django 4.2.7 on 2026-03-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="reservation",
            name="reservation_voyageu_36bd9f_idx",
        ),
        migrations.RemoveField(
            model_name="priceconfirmation",
            name="amadeus_offer_id",
        ),
        migrations.RemoveField(
            model_name="priceconfirmation",
            name="offer_data",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="amadeus_offer_id",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="confirmed_offer_data",
        ),
        migrations.AddField(
            model_name="priceconfirmation",
            name="confirmed_offer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="confirmed_offer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="original_offer",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flightsegment",
            name="per_passenger_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="flightsegment",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="passengerreservation",
            name="amadeus_traveler_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="passengerreservation",
            name="baggage_quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="passengerreservation",
            name="price_paid",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CARD", "Card"),
                    ("PAYPAL", "PayPal"),
                    ("BANK_TRANSFER", "Bank transfer"),
                    ("CASH", "Cash"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="priceconfirmation",
            name="confirmed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="priceconfirmation",
            name="offered_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="amadeus_booking_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="currency",
            field=models.CharField(default="EUR", max_length=3),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="last_confirmed_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_number",
            field=models.CharField(editable=False, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PRICE", "Waiting price confirmation"),
                    ("PRICE_CONFIRMED", "Price confirmed"),
                    ("BOOKING_PENDING", "Booking in progress"),
                    ("CONFIRMED", "Confirmed"),
                    ("CANCELLED", "Cancelled"),
                    ("EXPIRED", "Expired"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING_PRICE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="trip_type",
            field=models.CharField(
                choices=[
                    ("ALLER_SIMPLE", "One way"),
                    ("ALLER_RETOUR", "Round trip"),
                    ("MULTI_DESTINATION", "Multi city"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["voyageur"], name="reservation_voyageu_017fe8_idx"
            ),
        ),
    ]
