# Generated by Django 4.2.7 on 2026-03-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "reservations",
            "0002_remove_reservation_reservation_voyageu_36bd9f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="amadeus_pnr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
