# Generated by Django 4.2.7 on 2026-04-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0003_alter_reservation_amadeus_pnr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CARD", "Card"), ("CASH", "Cash"), ("DILEVERY", "Delivery")],
                max_length=20,
            ),
        ),
    ]
