# Generated by Django 4.2.7 on 2026-04-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0004_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("CARD", "Card"), ("CASH", "Cash"), ("DELIVERY", "DELIVERY")],
                max_length=20,
            ),
        ),
    ]
