# Generated by Django 4.2.7 on 2026-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0006_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUND_PENDING", "Refund Pending"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
