# Generated by Django 4.2.16 on 2026-05-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenant_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Agency/Company name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=100, unique=True)),
                ('domain_name', models.CharField(blank=True, help_text='Custom domain (e.g., travelagency.com)', max_length=255, null=True, unique=True)),
                ('subdomain', models.CharField(blank=True, help_text='Subdomain on main platform (e.g., agency.yourplatform.com)', max_length=100, null=True, unique=True)),
                ('db_name', models.CharField(max_length=100, unique=True)),
                ('db_user', models.CharField(max_length=100)),
                ('db_password', models.CharField(max_length=255)),
                ('db_host', models.CharField(default='postgres', max_length=255)),
                ('db_port', models.IntegerField(default=5432)),
                ('plan', models.CharField(choices=[('basic', 'Basic - 5 agents, 100 voyageurs'), ('pro', 'Pro - 20 agents, 1000 voyageurs'), ('enterprise', 'Enterprise - Unlimited')], default='basic', max_length=20)),
                ('max_agents', models.IntegerField(default=5)),
                ('max_voyageurs', models.IntegerField(default=100)),
                ('max_storage_mb', models.IntegerField(default=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('pending', 'Pending Setup'), ('deactivated', 'Deactivated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Agency-specific settings')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Enabled features')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuperAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Platform Owner'), ('super_admin', 'Super Administrator'), ('support', 'Support Agent'), ('billing', 'Billing Manager'), ('viewer', 'Read Only')], default='super_admin', max_length=20)),
                ('can_create_agencies', models.BooleanField(default=True)),
                ('can_delete_agencies', models.BooleanField(default=False)),
                ('can_access_all_agencies', models.BooleanField(default=True)),
                ('can_impersonate_any_user', models.BooleanField(default=False)),
                ('can_view_billing', models.BooleanField(default=False)),
                ('two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_secret', models.CharField(blank=True, max_length=100)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('create', 'Agency Created'), ('update', 'Agency Updated'), ('suspend', 'Agency Suspended'), ('activate', 'Agency Activated'), ('delete', 'Agency Deleted'), ('staff_add', 'Staff Added'), ('staff_remove', 'Staff Removed'), ('staff_role_change', 'Staff Role Changed')], max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('agency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tenant_management.agency')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('agency_admin', 'Agency Administrator'), ('agency_agent', 'Agency Agent'), ('agency_viewer', 'Agency Viewer')], max_length=20)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenant_management.agency')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(help_text="ID in agency's local database")),
                ('role', models.CharField(choices=[('agency_admin', 'Agency Administrator'), ('agency_agent', 'Agency Agent'), ('agency_viewer', 'Agency Viewer')], default='agency_agent', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('can_impersonate', models.BooleanField(default=False, help_text='Super admin can login as this user')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='tenant_management.agency')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agency', 'role', 'email'],
                'unique_together': {('agency', 'email'), ('agency', 'user_id')},
            },
        ),
    ]
