# Generated by Django 4.2.16 on 2026-05-01 14:03

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passport_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport_image'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='agency_local_id',
            field=models.IntegerField(blank=True, help_text="ID in agency's local DB for agents/voyageurs", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cross_agency',
            field=models.BooleanField(default=False, help_text='Indicates if user can access multiple agencies (for agents)'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='agency_id',
            field=models.IntegerField(blank=True, help_text='ID of the agency this voyageur belongs to', null=True),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='passport_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport_image'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='passport_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='passport_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='num_passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='nom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='num_passport',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='pays',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voyageur',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
