# Generated by Django 4.2.16 on 2026-05-03 11:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_date_joined_user_features_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passport_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport_image'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='passport_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='passport_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='passport_image'),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='passport_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voyageur',
            name='passport_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
